language: android
# Allows to install dependencies via apt-get when using Travis's new container-based infrastructure.
sudo: false
android:
  components:
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27" # https://github.com/travis-ci/travis-ci/issues/8651